### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by livrasand** [Ameth/ObraMundial#2]
Hola amigo, soy Livrädo Sandoval, Testigo de Jehová de México. Autor de Attendant Zoom (una aplicación para compartir multimedia en reuniones) y JWPUB Catalog (un catálogo de archivos propios de JWPUB). Estoy desarrollando una aplicación para ancianos y siervos ministeriales en Svelte y Electron. Me encantaría que pudieras apoyar mi proyecto. He mirado este proyecto y me ha gustado. ¿Qué dices? ¿Te nos unes? Actualmente somos 3 hermanos (de México, España y Brasil). Puede visitar mi sitio web: goatattendant.com y conocer Kingdom Hall Attendant.

**Comment by Ameth** [comment]
Hola Livrädo. Te saludo desde Colombia.

De antemano, te quiero felicitar por el trabajo que haces con las diferentes aplicaciones que has desarrollado. He visto el sitio web que me envías y se ve que quieres utilizar tus habilidades como desarrollador para el beneficio de los hermanos.

Sin embargo, no se si es prudente, o incluso bien visto, que una herramienta para ayudar a los hermanos en las congregaciones se deba comercializar de forma económica. La aplicación ObraMundial que yo desarrolle para algunas congregaciones en la ciudad donde vivo lleva 4 años funcionando y nunca se ha cobrado por el uso de la misma, a pesar que hay más de 20 congregaciones usándola y me siento feliz de que les ayude mucho a los ancianos en las tareas de organizar los informes, los grupos de salidas a la predicación y la información personal y de contacto de los hermanos, así como de reportes de los publicadores, precursores, etc. Es una herramienta que constantemente se le hacen nuevos features. Siento que prestamos un servicio voluntario para los hermanos, y es una forma de contribuir a Jehová.

De todas formas veo muy interesante tu proyecto, se ve muy completo y puede tener un uso futuro muy amplio. ¿Has pensado en hacerlo web 100%, no de escritorio con electron, así incluso se podría usar desde dispositivos móviles?
Yo he trabajado mucho tiempo en empresas donde he escalado aplicaciones de clientes a gran escala, si quieres te puedo ayudar en cómo realizarlo y entregarlo a las congregaciones de forma gratuita y crear estrategias de sostenibilidad para que de alguna forma te sea rentable. Así lo he hecho en ObraMundial.

Si estás de acuerdo, estaría feliz de poder ayudarte y sumar mi experiencia y conocimientos a tu proyecto.

Déjame saber tu respuesta.

Un saludo!

Ameth Ordoñez.
